### ISSUE TITLE
Release notes at AMO

### ISSUE THREAD

**Issue by grahamperrin** [qcl/QCLean#40]
https://addons.mozilla.org/addon/qclean/versions/ please, can you include release notes in the future? 

As you did for 0.5.8.24. 

Thanks

**Comment by qcl** [comment]
Now I added it for 0.5.8.31, thanks for your suggestion, I would include release notes in the future, thanks again :)

**Comment by grahamperrin** [comment]
@qcl https://addons.mozilla.org/en-GB/firefox/addon/qclean/versions/0.5.9.3/updateinfo/ is empty

**Comment by qcl** [comment]
@grahamperrin Thanks for reminding!
