### ISSUE TITLE
Seems to be blocking almost all posts

### ISSUE THREAD

**Issue by davinderc** [qcl/QCLean#41]
I'm not sure how to report this issue, but a few days ago I wasn't able to see a number of posts, especially ones I had commented on, and then most recently it seemed all posts were not being shown. Basically FB would load and then the posts that were supposed to be loading would disappear after showing initially for a second. I thought it was uBlock, but disabling that on FB didn't fix anything.

Today I checked the dev console and saw that QClean was doing this (didn't even realize I had this addon anymore) and after disabling it in Firefox I could suddenly see FB posts again. What more information can I provide to debug this issue, as QClean is completely unusable as it is.

**Comment by qcl** [comment]
Thanks for your reporting and I just checked code, then I found some of old rules which is used to identify sponsored post mismatched normal posts. Sorry for your inconvenience, I am working on a fix and will release it as soon as I can. 

Thanks for your reporting again :)

**Comment by qcl** [comment]
Just submitted a fix to Firefox add-ons, please wait for auto update or manually trigger update on Firefox, thanks!

**Comment by davinderc** [comment]
Thank you! It was no inconvenience, I'm happy to report issues that I find and I really appreciate you creating this tool for us! 🥇

**Comment by davinderc** [comment]
Have a coffee, or tea, or whatever you prefer, paid by me (sent it by Paypal) ;)
